/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_dhbw_mannheim_cloudraid_jni_RaidAccessInterface */

#ifndef _Included_de_dhbw_mannheim_cloudraid_jni_RaidAccessInterface
#define _Included_de_dhbw_mannheim_cloudraid_jni_RaidAccessInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_dhbw_mannheim_cloudraid_jni_RaidAccessInterface
 * Method:    mergeInterface
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_mannheim_cloudraid_jni_RaidAccessInterface_mergeInterface
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     de_dhbw_mannheim_cloudraid_jni_RaidAccessInterface
 * Method:    splitInterface
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_dhbw_mannheim_cloudraid_jni_RaidAccessInterface_splitInterface
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
