/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_dhbw_mannheim_cloudraid_jni_RaidAccessInterface */

#ifndef _Included_de_dhbw_mannheim_cloudraid_jni_RaidAccessInterface
#define _Included_de_dhbw_mannheim_cloudraid_jni_RaidAccessInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_dhbw_mannheim_cloudraid_jni_RaidAccessInterface
 * Method:    mergeBitInterface
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_dhbw_mannheim_cloudraid_jni_RaidAccessInterface_mergeBitInterface
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     de_dhbw_mannheim_cloudraid_jni_RaidAccessInterface
 * Method:    splitBitInterface
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_dhbw_mannheim_cloudraid_jni_RaidAccessInterface_splitBitInterface
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     de_dhbw_mannheim_cloudraid_jni_RaidAccessInterface
 * Method:    mergeByteInterface
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_dhbw_mannheim_cloudraid_jni_RaidAccessInterface_mergeByteInterface
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     de_dhbw_mannheim_cloudraid_jni_RaidAccessInterface
 * Method:    splitByteInterface
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_dhbw_mannheim_cloudraid_jni_RaidAccessInterface_splitByteInterface
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
