/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface */

#ifndef _Included_de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface
#define _Included_de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface
#ifdef __cplusplus
extern "C" {
#endif
#undef de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_SUCCESS_MERGE
#define de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_SUCCESS_MERGE 1L
#undef de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_MEMERR_BUF
#define de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_MEMERR_BUF 2L
#undef de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_MEMERR_DEV
#define de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_MEMERR_DEV 4L
#undef de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_MEMERR_SHA
#define de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_MEMERR_SHA 8L
#undef de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_OPENERR_DEV0
#define de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_OPENERR_DEV0 16L
#undef de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_OPENERR_DEV1
#define de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_OPENERR_DEV1 32L
#undef de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_OPENERR_DEV2
#define de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_OPENERR_DEV2 64L
#undef de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_OPENERR_IN
#define de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_OPENERR_IN 128L
#undef de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_OPENERR_OUT
#define de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_OPENERR_OUT 256L
#undef de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_METADATA_ERROR
#define de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_METADATA_ERROR 512L
#undef de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_SUCCESS_SPLIT
#define de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface_SUCCESS_SPLIT 1024L
/*
 * Class:     de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface
 * Method:    mergeInterface
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_dhbw_1mannheim_cloudraid_core_impl_jni_RaidAccessInterface_mergeInterface
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface
 * Method:    splitInterface
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_dhbw_1mannheim_cloudraid_core_impl_jni_RaidAccessInterface_splitInterface
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_dhbw_1mannheim_cloudraid_core_impl_jni_RaidAccessInterface_getName
  (JNIEnv *, jclass);

/*
 * Class:     de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface
 * Method:    getVendor
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_dhbw_1mannheim_cloudraid_core_impl_jni_RaidAccessInterface_getVendor
  (JNIEnv *, jclass);

/*
 * Class:     de_dhbw_mannheim_cloudraid_core_impl_jni_RaidAccessInterface
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_dhbw_1mannheim_cloudraid_core_impl_jni_RaidAccessInterface_getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
