/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RaidAccessInterface */

#ifndef _Included_RaidAccessInterface
#define _Included_RaidAccessInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RaidAccessInterface
 * Method:    splitInterface
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_RaidAccessInterface_splitInterface
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     RaidAccessInterface
 * Method:    mergeInterface
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_RaidAccessInterface_mergeInterface
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
